Make product-key optional
zepben/.github pull request #33
Opened 2024-05-17 03:21 UTC by alourie

This fix syncs the work done previously for the snapshot flows where "product-key" value is automatically detected from docs/docusaurus.conf.js to all other release-with-docs flows.

If the repo using any of these flows deploys documentation to a custom-named site, "product-key" can be overwritten in the appropriate github action in the repo.

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [X] I have performed a self review of my own code (including checking issues raised when creating the PR).
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
- [X] I have rebased onto the target branch (usually main).

2024-05-17 03:21 UTC, ryanjcoleman commented
Task linked: [OPS-202 Update all flows to optional product-key](https://app.clickup.com/t/6929263/OPS-202)

2024-05-19 08:33 UTC, kgreav requested changes
Probably makes sense to also make this change to snapshot builds right?

Also, I see npm-lib-* doesn't currently build docs, but it should. Can you update it to bring it into line with these workflows?

2024-05-19 09:35 UTC, alourie commented
I'll update the npm-* stuff, however I though all snapshots already have these - as I copied the steps from there. I'll recheck.

2024-05-19 22:18 UTC, kgreav commented
I didn't check - assumed not, so you are probably right.

2024-05-20 02:54 UTC, alourie commented
@kgreav npm-lib doesn't have the docs indeed, so I'll deal with those in a separate PR. Snapshots are, however, all good. So this can be merged if it's blocking others.

2024-05-20 05:26 UTC, merged