Ops 279 multiple artifacts maven
zepben/.github pull request #61
Opened 2024-11-26 07:28 UTC by ramonbouckaert

# Description

Allow for Maven repos using the `maven-app-release.yml`, `maven-app-release-with-docs.yml`, and `maven-app-snapshot.yml` workflows to support outputting multiple files as artifacts and release assets, rather than a single JAR file.

This is done in a backwards-compatible way with repos that expect to output a single JAR. When a maven project is built, it produces a `target/` folder that looks roughly like this:
```
classes/
coverage-reports/
generated-sources/
generated-test-sources/
kotlin-ic/
maven-status/
site/
surefire-reports/
test-classes/
**project-version.jar**
original-project-version.jar
```

Under the old workflows, **project-version.jar** would be identified as the build artifact and attached as a release asset.

With these changes, every file in the top-level of the `target/` directory, ignoring sub-directories, will be added, with the exception of the file that matches the pattern `original-*.jar`.

Maven repos that use these workflows can now include additional artifacts in the release, by configuring the pom/maven plugins to ensure that those files are outputted in the top-level of the `target/` directory alongside **project-version.jar**, like so:

```
classes/
coverage-reports/
generated-sources/
generated-test-sources/
kotlin-ic/
maven-status/
site/
surefire-reports/
test-classes/
**project-version.jar**
original-project-version.jar
**additional-artifact.dll**
**additional-artifact.so**
**another-additional-artifact.conf**
**yet-another-additional-artifact.md**
```

When producing a release using this new workflow, **project-version.jar**, **additional-artifact.dll**, **additional-artifact.so**, **another-additional-artifact.conf** and **yet-another-additional-artifact.md** will all be included as release assets.

# Associated tasks

Needed for https://github.com/zepben/ednar-app-server/pull/376, where a wrapper.conf file needs to be included with future releases of the EDNAR App Server. A similar pattern will be used for other maven projects once this change is merged in.

# Test Steps

To validate this works with multiple artifacts, check out https://github.com/zepben/ednar-app-server/pull/376 and produce a snapshot release using CI to validate that multiple build artifacts are produced.

To validate this is backwards-compatible with repos that are unchanged except for the use of the new workflow, you can see the latest "release" of the EDNAR LDAP Polling service: https://github.com/zepben/ldap-user-polling-service (I will be erasing this release after this branch is merged)

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
- ~[ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
- ~[ ] I have commented my code in any hard-to-understand or hacky areas.~
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).

### Documentation
- ~[ ] I have updated the changelog.~
- ~[ ] I have updated any documentation required for these changes.~

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

Should not be a breaking change - should be backwards-compatible with the previous maven-app-* workflows. Regardless, I have communicated this change on slack.

2024-11-26 07:28 UTC, ryanjcoleman commented
Task linked: [OPS-279 Support multiple artifacts for Maven releases](https://app.clickup.com/t/6929263/OPS-279)

2024-11-27 04:39 UTC, alourie requested changes
Looking good, a few minor comments

2024-11-27 04:39 UTC, alourie commented on .github/workflows/maven-app-release-with-docs.yml
> +          cp target/* -t .artifact-$artifact || :
nit: with these `|| :` - I'd probably not do it for `cp` and let it fail if there's an issue, and for `rm` you can always use `-f` which doesn't seem to return error. They look more natural commands and less confusing.

2024-11-27 04:49 UTC, ramonbouckaert commented on .github/workflows/maven-app-release.yml
> -          name: ${{ needs.deploy.outputs.artifact }}
If you omit the `name` property, it downloads every artifact, which is the desired behaviour: https://github.com/actions/download-artifact/blob/main/README.md

2024-11-27 04:56 UTC, ramonbouckaert commented on .github/workflows/maven-app-release-with-docs.yml
> +          echo "artifactId=$(echo $artifactId)" >> ${GITHUB_OUTPUT}
Fixed in most recent commit

2024-12-11 23:19 UTC, alourie commented
Let's resolve conflicts with base, otherwise looks good!

2024-12-11 23:20 UTC, alourie commented on .github/workflows/maven-app-release-with-docs.yml
> +          cp target/* -t .artifact-$artifact || :
we'll leave it as is, if it bothers me too much I'll look how to do it differently

2025-02-19 04:55 UTC, alourie commented
@ramonbouckaert this seems to have dropped from the radar, do we still use need it merged?

2025-02-19 04:56 UTC, ramonbouckaert commented
> @ramonbouckaert this seems to have dropped from the radar, do we still use need it merged?

It does - let me rebase and resolve conflicts now.

2025-02-19 05:27 UTC, ramonbouckaert commented
@alourie Rebased. Want to take another squiz and approve if you're happy.

2025-02-19 06:21 UTC, alourie approved these changes
Looks great Ramon, we can merge it.

2025-02-19 07:32 UTC, merged